title: TrustworthyAI
description: Research, notes, and thoughts on trustworthy AI
url: "https://ianchou89.github.io/TrustworthyAI/"
baseurl: "/TrustworthyAI"

remote_theme: mmistakes/minimal-mistakes

author:
  name: TrustworthyAI
  bio: Research on reliable, ethical, and robust AI
  location: Internet

minimal_mistakes_skin: dark

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
permalink: /:categories/:title/
timezone: UTC
